# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[main]]
identifier = "about"
name = "关于我"
url = "/about/"  # 注意结尾的斜杠
weight = 3 

[main.params]
icon = "user"       # 使用用户图标

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/CaiJimmy/hugo-theme-stack"

[social.params]
icon = "brand-github"

[[social]]
identifier = "twitter"
name = "Twitter"
url = "https://twitter.com"

[social.params]
icon = "brand-twitter"

[[social]]
identifier = "email"
name = "邮件联系"
url = "mailto:your-email@example.com"

[social.params]
icon = "mail"
